<?php

// Exit if accessed directly
if ( !defined('ABSPATH')) exit;

if ( !class_exists('CUAR_CountryHelper')) :

    /**
     * Gathers some helper functions to facilitate some coding
     */
    class CUAR_CountryHelper
    {

        public static function getCountryName($code)
        {
            $countries = self::getCountries();

            return isset($countries[$code]) ? $countries[$code] : '-';
        }

        public static function getCountries()
        {
            return array(
                ''   => '',
                'US' => __('United States', 'cuar'),
                'CA' => __('Canada', 'cuar'),
                'GB' => __('United Kingdom', 'cuar'),
                'AF' => __('Afghanistan', 'cuar'),
                'AX' => __('&#197;land Islands', 'cuar'),
                'AL' => __('Albania', 'cuar'),
                'DZ' => __('Algeria', 'cuar'),
                'AS' => __('American Samoa', 'cuar'),
                'AD' => __('Andorra', 'cuar'),
                'AO' => __('Angola', 'cuar'),
                'AI' => __('Anguilla', 'cuar'),
                'AQ' => __('Antarctica', 'cuar'),
                'AG' => __('Antigua and Barbuda', 'cuar'),
                'AR' => __('Argentina', 'cuar'),
                'AM' => __('Armenia', 'cuar'),
                'AW' => __('Aruba', 'cuar'),
                'AU' => __('Australia', 'cuar'),
                'AT' => __('Austria', 'cuar'),
                'AZ' => __('Azerbaijan', 'cuar'),
                'BS' => __('Bahamas', 'cuar'),
                'BH' => __('Bahrain', 'cuar'),
                'BD' => __('Bangladesh', 'cuar'),
                'BB' => __('Barbados', 'cuar'),
                'BY' => __('Belarus', 'cuar'),
                'BE' => __('Belgium', 'cuar'),
                'BZ' => __('Belize', 'cuar'),
                'BJ' => __('Benin', 'cuar'),
                'BM' => __('Bermuda', 'cuar'),
                'BT' => __('Bhutan', 'cuar'),
                'BO' => __('Bolivia', 'cuar'),
                'BQ' => __('Bonaire, Saint Eustatius and Saba', 'cuar'),
                'BA' => __('Bosnia and Herzegovina', 'cuar'),
                'BW' => __('Botswana', 'cuar'),
                'BV' => __('Bouvet Island', 'cuar'),
                'BR' => __('Brazil', 'cuar'),
                'IO' => __('British Indian Ocean Territory', 'cuar'),
                'BN' => __('Brunei Darrussalam', 'cuar'),
                'BG' => __('Bulgaria', 'cuar'),
                'BF' => __('Burkina Faso', 'cuar'),
                'BI' => __('Burundi', 'cuar'),
                'KH' => __('Cambodia', 'cuar'),
                'CM' => __('Cameroon', 'cuar'),
                'CV' => __('Cape Verde', 'cuar'),
                'KY' => __('Cayman Islands', 'cuar'),
                'CF' => __('Central African Republic', 'cuar'),
                'TD' => __('Chad', 'cuar'),
                'CL' => __('Chile', 'cuar'),
                'CN' => __('China', 'cuar'),
                'CX' => __('Christmas Island', 'cuar'),
                'CC' => __('Cocos Islands', 'cuar'),
                'CO' => __('Colombia', 'cuar'),
                'KM' => __('Comoros', 'cuar'),
                'CD' => __('Congo, Democratic People\'s Republic', 'cuar'),
                'CG' => __('Congo, Republic of', 'cuar'),
                'CK' => __('Cook Islands', 'cuar'),
                'CR' => __('Costa Rica', 'cuar'),
                'CI' => __('Cote d\'Ivoire', 'cuar'),
                'HR' => __('Croatia/Hrvatska', 'cuar'),
                'CU' => __('Cuba', 'cuar'),
                'CW' => __('Cura&Ccedil;ao', 'cuar'),
                'CY' => __('Cyprus', 'cuar'),
                'CZ' => __('Czech Republic', 'cuar'),
                'DK' => __('Denmark', 'cuar'),
                'DJ' => __('Djibouti', 'cuar'),
                'DM' => __('Dominica', 'cuar'),
                'DO' => __('Dominican Republic', 'cuar'),
                'TP' => __('East Timor', 'cuar'),
                'EC' => __('Ecuador', 'cuar'),
                'EG' => __('Egypt', 'cuar'),
                'GQ' => __('Equatorial Guinea', 'cuar'),
                'SV' => __('El Salvador', 'cuar'),
                'ER' => __('Eritrea', 'cuar'),
                'EE' => __('Estonia', 'cuar'),
                'ET' => __('Ethiopia', 'cuar'),
                'FK' => __('Falkland Islands', 'cuar'),
                'FO' => __('Faroe Islands', 'cuar'),
                'FJ' => __('Fiji', 'cuar'),
                'FI' => __('Finland', 'cuar'),
                'FR' => __('France', 'cuar'),
                'GF' => __('French Guiana', 'cuar'),
                'PF' => __('French Polynesia', 'cuar'),
                'TF' => __('French Southern Territories', 'cuar'),
                'GA' => __('Gabon', 'cuar'),
                'GM' => __('Gambia', 'cuar'),
                'GE' => __('Georgia', 'cuar'),
                'DE' => __('Germany', 'cuar'),
                'GR' => __('Greece', 'cuar'),
                'GH' => __('Ghana', 'cuar'),
                'GI' => __('Gibraltar', 'cuar'),
                'GL' => __('Greenland', 'cuar'),
                'GD' => __('Grenada', 'cuar'),
                'GP' => __('Guadeloupe', 'cuar'),
                'GU' => __('Guam', 'cuar'),
                'GT' => __('Guatemala', 'cuar'),
                'GG' => __('Guernsey', 'cuar'),
                'GN' => __('Guinea', 'cuar'),
                'GW' => __('Guinea-Bissau', 'cuar'),
                'GY' => __('Guyana', 'cuar'),
                'HT' => __('Haiti', 'cuar'),
                'HM' => __('Heard and McDonald Islands', 'cuar'),
                'VA' => __('Holy See (City Vatican State)', 'cuar'),
                'HN' => __('Honduras', 'cuar'),
                'HK' => __('Hong Kong', 'cuar'),
                'HU' => __('Hungary', 'cuar'),
                'IS' => __('Iceland', 'cuar'),
                'IN' => __('India', 'cuar'),
                'ID' => __('Indonesia', 'cuar'),
                'IR' => __('Iran', 'cuar'),
                'IQ' => __('Iraq', 'cuar'),
                'IE' => __('Ireland', 'cuar'),
                'IM' => __('Isle of Man', 'cuar'),
                'IL' => __('Israel', 'cuar'),
                'IT' => __('Italy', 'cuar'),
                'JM' => __('Jamaica', 'cuar'),
                'JP' => __('Japan', 'cuar'),
                'JE' => __('Jersey', 'cuar'),
                'JO' => __('Jordan', 'cuar'),
                'KZ' => __('Kazakhstan', 'cuar'),
                'KE' => __('Kenya', 'cuar'),
                'KI' => __('Kiribati', 'cuar'),
                'KW' => __('Kuwait', 'cuar'),
                'KG' => __('Kyrgyzstan', 'cuar'),
                'LA' => __('Lao People\'s Democratic Republic', 'cuar'),
                'LV' => __('Latvia', 'cuar'),
                'LB' => __('Lebanon', 'cuar'),
                'LS' => __('Lesotho', 'cuar'),
                'LR' => __('Liberia', 'cuar'),
                'LY' => __('Libyan Arab Jamahiriya', 'cuar'),
                'LI' => __('Liechtenstein', 'cuar'),
                'LT' => __('Lithuania', 'cuar'),
                'LU' => __('Luxembourg', 'cuar'),
                'MO' => __('Macau', 'cuar'),
                'MK' => __('Macedonia', 'cuar'),
                'MG' => __('Madagascar', 'cuar'),
                'MW' => __('Malawi', 'cuar'),
                'MY' => __('Malaysia', 'cuar'),
                'MV' => __('Maldives', 'cuar'),
                'ML' => __('Mali', 'cuar'),
                'MT' => __('Malta', 'cuar'),
                'MH' => __('Marshall Islands', 'cuar'),
                'MQ' => __('Martinique', 'cuar'),
                'MR' => __('Mauritania', 'cuar'),
                'MU' => __('Mauritius', 'cuar'),
                'YT' => __('Mayotte', 'cuar'),
                'MX' => __('Mexico', 'cuar'),
                'FM' => __('Micronesia', 'cuar'),
                'MD' => __('Moldova, Republic of', 'cuar'),
                'MC' => __('Monaco', 'cuar'),
                'MN' => __('Mongolia', 'cuar'),
                'ME' => __('Montenegro', 'cuar'),
                'MS' => __('Montserrat', 'cuar'),
                'MA' => __('Morocco', 'cuar'),
                'MZ' => __('Mozambique', 'cuar'),
                'MM' => __('Myanmar', 'cuar'),
                'NA' => __('Namibia', 'cuar'),
                'NR' => __('Nauru', 'cuar'),
                'NP' => __('Nepal', 'cuar'),
                'NL' => __('Netherlands', 'cuar'),
                'AN' => __('Netherlands Antilles', 'cuar'),
                'NC' => __('New Caledonia', 'cuar'),
                'NZ' => __('New Zealand', 'cuar'),
                'NI' => __('Nicaragua', 'cuar'),
                'NE' => __('Niger', 'cuar'),
                'NG' => __('Nigeria', 'cuar'),
                'NU' => __('Niue', 'cuar'),
                'NF' => __('Norfolk Island', 'cuar'),
                'KR' => __('North Korea', 'cuar'),
                'MP' => __('Northern Mariana Islands', 'cuar'),
                'NO' => __('Norway', 'cuar'),
                'OM' => __('Oman', 'cuar'),
                'PK' => __('Pakistan', 'cuar'),
                'PW' => __('Palau', 'cuar'),
                'PS' => __('Palestinian Territories', 'cuar'),
                'PA' => __('Panama', 'cuar'),
                'PG' => __('Papua New Guinea', 'cuar'),
                'PY' => __('Paraguay', 'cuar'),
                'PE' => __('Peru', 'cuar'),
                'PH' => __('Phillipines', 'cuar'),
                'PN' => __('Pitcairn Island', 'cuar'),
                'PL' => __('Poland', 'cuar'),
                'PT' => __('Portugal', 'cuar'),
                'PR' => __('Puerto Rico', 'cuar'),
                'QA' => __('Qatar', 'cuar'),
                'XK' => __('Republic of Kosovo', 'cuar'),
                'RE' => __('Reunion Island', 'cuar'),
                'RO' => __('Romania', 'cuar'),
                'RU' => __('Russian Federation', 'cuar'),
                'RW' => __('Rwanda', 'cuar'),
                'BL' => __('Saint Barth&eacute;lemy', 'cuar'),
                'SH' => __('Saint Helena', 'cuar'),
                'KN' => __('Saint Kitts and Nevis', 'cuar'),
                'LC' => __('Saint Lucia', 'cuar'),
                'MF' => __('Saint Martin (French)', 'cuar'),
                'SX' => __('Saint Martin (Dutch)', 'cuar'),
                'PM' => __('Saint Pierre and Miquelon', 'cuar'),
                'VC' => __('Saint Vincent and the Grenadines', 'cuar'),
                'SM' => __('San Marino', 'cuar'),
                'ST' => __('S&atilde;o Tom&eacute; and Pr&iacute;ncipe', 'cuar'),
                'SA' => __('Saudi Arabia', 'cuar'),
                'SN' => __('Senegal', 'cuar'),
                'RS' => __('Serbia', 'cuar'),
                'SC' => __('Seychelles', 'cuar'),
                'SL' => __('Sierra Leone', 'cuar'),
                'SG' => __('Singapore', 'cuar'),
                'SK' => __('Slovak Republic', 'cuar'),
                'SI' => __('Slovenia', 'cuar'),
                'SB' => __('Solomon Islands', 'cuar'),
                'SO' => __('Somalia', 'cuar'),
                'ZA' => __('South Africa', 'cuar'),
                'GS' => __('South Georgia', 'cuar'),
                'KP' => __('South Korea', 'cuar'),
                'SS' => __('South Sudan', 'cuar'),
                'ES' => __('Spain', 'cuar'),
                'LK' => __('Sri Lanka', 'cuar'),
                'SD' => __('Sudan', 'cuar'),
                'SR' => __('Suriname', 'cuar'),
                'SJ' => __('Svalbard and Jan Mayen Islands', 'cuar'),
                'SZ' => __('Swaziland', 'cuar'),
                'SE' => __('Sweden', 'cuar'),
                'CH' => __('Switzerland', 'cuar'),
                'SY' => __('Syrian Arab Republic', 'cuar'),
                'TW' => __('Taiwan', 'cuar'),
                'TJ' => __('Tajikistan', 'cuar'),
                'TZ' => __('Tanzania', 'cuar'),
                'TH' => __('Thailand', 'cuar'),
                'TL' => __('Timor-Leste', 'cuar'),
                'TG' => __('Togo', 'cuar'),
                'TK' => __('Tokelau', 'cuar'),
                'TO' => __('Tonga', 'cuar'),
                'TT' => __('Trinidad and Tobago', 'cuar'),
                'TN' => __('Tunisia', 'cuar'),
                'TR' => __('Turkey', 'cuar'),
                'TM' => __('Turkmenistan', 'cuar'),
                'TC' => __('Turks and Caicos Islands', 'cuar'),
                'TV' => __('Tuvalu', 'cuar'),
                'UG' => __('Uganda', 'cuar'),
                'UA' => __('Ukraine', 'cuar'),
                'AE' => __('United Arab Emirates', 'cuar'),
                'UY' => __('Uruguay', 'cuar'),
                'UM' => __('US Minor Outlying Islands', 'cuar'),
                'UZ' => __('Uzbekistan', 'cuar'),
                'VU' => __('Vanuatu', 'cuar'),
                'VE' => __('Venezuela', 'cuar'),
                'VN' => __('Vietnam', 'cuar'),
                'VG' => __('Virgin Islands (British)', 'cuar'),
                'VI' => __('Virgin Islands (USA)', 'cuar'),
                'WF' => __('Wallis and Futuna Islands', 'cuar'),
                'EH' => __('Western Sahara', 'cuar'),
                'WS' => __('Western Samoa', 'cuar'),
                'YE' => __('Yemen', 'cuar'),
                'ZM' => __('Zambia', 'cuar'),
                'ZW' => __('Zimbabwe', 'cuar'),
            );
        }


    }

endif; // class_exists CUAR_CountryHelper